name: GitHub Actions Workload Identity Demo
on: [push]
permissions:
    contents: "read"
    id-token: "write"
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"


      - name: Authenticate with Google Cloud
        run: gcloud auth application-default login


      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: projects/129781850284/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: terraform-sa@terraform-test-384414.iam.gserviceaccount.com




      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"
        with:
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}


      - name: Terraform init    
        run: terraform init

      - name: Terraform plan
        run: terraform plan
        working-directory: ../terraform-test

      - name: Terraform apply
        run: terraform apply -auto-approve 
        working-directory: ../terraform-test
         
        


